### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by equinusocio** [jmadler/emoji-picker#123]
Hi, just to let you know that Apple Emoji images are under copyright and they can't be used without the license.

https://emojipedia.org/licensing/
https://blog.emojipedia.org/who-owns-emoji/
https://www.plagiarismtoday.com/2018/04/10/copyright-and-emojis/

You should use an emoji set that provide an appropriate license for OS projects. Here some open source alternatives:

https://twemoji.twitter.com
https://openmoji.org

**Comment by tiomanisland** [comment]
Because it looks better!

**Comment by adeopura4** [comment]
Hi - wondering if anyone has a version of this library with an emoji set that is based on a more permissive license. Thank you.

**Comment by equinusocio** [comment]
@adeopura4 You can fork this, and replace the png sprites with a different set. Like https://openmoji.org/

**Comment by adeopura4** [comment]
@equinusocio - Thank you for your comment. I was trying to replace the Apple emojis you have with the Twiiter emojis (for instance). I think one question I have is how did you create the https://github.com/OneSignal/emoji-picker/blob/master/lib/js/config.js? Is that somehow  generated from the spritesheet using some other library/program? Specifically, how did you get the emoji_data Json.

Since the Twitter spritesheet has a different number of images etc, I have to have a change the config.json. However, I am not sure exactly what values to change in the config.json.

Thank you for your help.
